lab4.zip: makefile.txt *.c *.h lab4readme
	zip lab4.zip makefile.txt *.c *.h lab4readme
	rm -rf install
	mkdir install
	unzip lab4.zip -d install
	make -C install lab4
	
lab4: lab4.o linkedlist.o PSW.o Test0.o Test1.o Test2.o Test3.o
	gcc lab4.o linkedlist.o PSW.o Test0.o Test1.o Test2.o Test3.o -o lab4
	
lab4.o: lab4.c PSW.c linkedlist.c constants.h ballstructs.h
	gcc -ansi -pedantic -g -c lab4.c
	
linkedlist.o: linkedlist.c linkedlist.h
	gcc -ansi -pedantic -g -c linkedlist.c
	
PSW.o: PSW.c PSW.h
	gcc -ansi -pedantic -g -c PSW.c
	
Test0.o: Test0.c
	gcc -ansi -pedantic -g -c Test0.c
	
Test1.o: Test1.c
	gcc -ansi -pedantic -g -c Test1.c
	
Test2.o: Test2.c linkedlist.c ballstructs.h
	gcc -ansi -pedantic -g -c Test2.c
	
Test3.o: Test3.c linkedlist.c ballstructs.h
	gcc -ansi -pedantic -g -c Test3.c
	
clean:
	rm -rf *.o lab4
	
	